{{ $application := default dict .Values.application }}
{{ $pipeline := default dict .Values.pipeline }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $application.name }}-image-puller-default
  namespace: {{ $application.environments.cicd }}
subjects:
- kind: ServiceAccount
  name: {{ $pipeline.sa.default }}
  namespace: {{ $application.environments.cicd }}
roleRef:
  kind: ClusterRole
  name: system:image-puller
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $application.name }}-image-puller-triggers
  namespace: {{ $application.environments.cicd }}
subjects:
- kind: ServiceAccount
  name: {{ $pipeline.sa.triggers }}
  namespace: {{ $application.environments.cicd }}
roleRef:
  kind: ClusterRole
  name: system:image-puller
  apiGroup: rbac.authorization.k8s.io
---
{{- if .Values.repositories }}
{{- range $repo := .Values.repositories }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ $repo.id }}
  namespace: {{ $application.environments.development }}
  labels:
    app: {{ $application.name }}
    repo: {{ $repo.name }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $application.name }}-image-puller-{{ $repo.id }}
  namespace: {{ $application.environments.cicd }}
subjects:
- kind: ServiceAccount
  name: {{ $pipeline.sa.triggers }}
  namespace: {{ $application.environments.development }}
roleRef:
  kind: ClusterRole
  name: system:image-puller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ $repo.id }}
  namespace: {{ $application.environments.production }}
  labels:
    app: {{ $application.name }}
    repo: {{ $repo.name }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $application.name }}-image-puller-{{ $repo.id }}
  namespace: {{ $application.environments.cicd }}
subjects:
- kind: ServiceAccount
  name: {{ $pipeline.sa.triggers }}
  namespace: {{ $application.environments.production }}
roleRef:
  kind: ClusterRole
  name: system:image-puller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ $application.name }}-production-{{ $repo.id }}
  namespace: {{ $application.environments.cicd }}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ $application.name }}-development-{{ $repo.id }}
  namespace: {{ $application.environments.cicd }}
  labels:
    app: {{ $application.name }}
    repo: {{ $repo.id }}
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/{{ $application.environments.development }}/{{ $application.name }}-development-{{ $repo.id }}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ $application.name }}-production-{{ $repo.id }}
  namespace: {{ $application.environments.cicd }}
  labels:
    app: {{ $application.name }}
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/{{ $application.environments.production }}/{{ $application.name }}-production-{{ $repo.id }}
{{- end }}
{{- end }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ $application.name }}-documentation
  namespace: {{ $application.environments.cicd }}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ $application.name }}-documentation
  namespace: {{ $application.environments.cicd }}
  labels:
    app: {{ $application.name }}
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/{{ $application.environments.development }}/{{ $application.name }}-documentation
