apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-performance
  namespace: {{ .Values.application.environments.cicd }}
spec:
  params:
    - name: hostname
      description: hostname to be stressed
      default: "false"
      type: string
    - name: revision-type
      description: revision type
      type: string
  steps:
    - name: test-performance
      image: registry.redhat.io/openshift4/ose-cli:latest
      resources: {}
      script: |
        #!/bin/bash
        if [ "$(inputs.params.revision-type)" == "feature" ] || [ "$(inputs.params.revision-type)" == "develop" ]; then
          echo Endpoint: $(params.hostname)
          DURATION=10       # how long should load be applied ? - in seconds
          TPS=100           # number of requests per second
          end=$((SECONDS+$DURATION))
          #start load
          while [ $SECONDS -lt $end ];
          do
            for ((i=1;i<=$TPS;i++)); do
              curl -X POST https://$(params.hostname) -H 'Accept: application/json' -H 'Authorization: Bearer xxxxxxxxxxxxx' -H 'Content-Type: application/json' -d '{}' -o /dev/null -s -w '%{time_starttransfer}\n' >> response-times.log &
            done
            sleep 1
          done
          wait
          #end load
          echo "Load test has been completed"
          exit 0
        fi
      securityContext:
        runAsUser: 0
